name: Sync Leetcode

on:
  workflow_dispatch:      # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'   # Runs every day at midnight

permissions:              # <--- ADDED THIS SECTION
  contents: write         # Grants permission to commit files to the repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
